### ISSUE TITLE
Usability fix for Windows

### ISSUE THREAD

**Issue by visualcookie** [daneden/photos.daneden.me#3]
I know, you're using Mac and might also use a Magic Mouse, but I'm actually not able to scroll through the picture container. Maybe invert the default scrolling functionality from vertical to horizontal with something like [jInvertScroll](http://www.pixxelfactory.net/jInvertScroll/).

**Comment by nil** [comment]
To scroll horizontally, you can hold Shift while scrolling.

**Comment by daneden** [comment]
This should have been fixed by 001d0ea2321f845cc18df9a404a2957b4888ec53
